Develop
amilcar-sr/JustifiedTextView pull request #3
Opened 2016-12-31 21:03 UTC by JimmyAMarquez

Hi,

I've been working on this repo, I think It is a great a idea to have such a library, I added support to Html.FromHtml and made some small plumbing, please let me know your thoughts.

Thank you!
Jimmy.

2017-03-21 17:54 UTC, pablomarti requested changes
So far so good! in a quick check it seems really good

2017-03-21 17:54 UTC, pablomarti commented on ExampleApp/src/main/java/com/codesgood/example/activities/MainActivity.java
> +        String strTest = getResources().getString(R.string.text_sample_styled);
This could be managed in other method and called from here

2017-03-21 17:54 UTC, pablomarti commented on ExampleApp/src/main/java/com/codesgood/example/activities/util/StringHtmlUtils.java
> +    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
This condition and assignment may be shorter, don't you think?

2017-03-21 17:54 UTC, pablomarti commented on JustifiedTextView/src/main/java/com/codesgood/views/JustifiedTextView.java
> +    if ((charSequence instanceof SpannedString)) {
I get it, but this segment is too complex, is there a way to split it out?

2017-03-21 17:54 UTC, pablomarti commented on JustifiedTextView/src/main/java/com/codesgood/views/JustifiedTextView.java
> +    if ((charSequence instanceof SpannedString)) {
And also the following methods; I like the new patterns to have tiny methods

2017-03-21 17:59 UTC, pablomarti commented
What do you think about this @amilcar-sr ?  Looks like a great project!

2017-03-21 21:12 UTC, jhurtado-applaudostudios commented on ExampleApp/src/main/java/com/codesgood/example/activities/util/StringHtmlUtils.java
> +    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
return android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N
                ? Html.fromHtml(html, Html.FROM_HTML_MODE_LEGACY)
                : Html.fromHtml(html);

2017-03-21 21:18 UTC, jhurtado-applaudostudios commented on JustifiedTextView/src/main/java/com/codesgood/views/model/SpanHolder.java
> +  private CharacterStyle[] spans;
Could be a good idea to add 'm' prefix to follow code style

2017-03-26 08:57 UTC, amilcar-sr commented
Thanks a lot for your contribution @JimmyAMarquez ! You've done a great job 👌  I think this is a good improvement for the project 😄 now... before accepting this Pull Request, I'd just like you to change the string example you added for the HTML support, I'm just trying to keep the code as neutral as possible... without political nor religious stuff :) 

And again... I'm sorry I didn't review this before, I got the email notification... but these days I've had a lot of things going on I totally forgot about it.

2017-03-27 02:50 UTC, JimmyAMarquez commented
Hey @amilcar-sr  Thank you very much for checking this pull request, I really like this project I think it is useful! I just changed the sample text to have a Lorem Ipsum generic text so yeah it now supports Html styling, you can check changes in last commit to this [PR ](https://github.com/amilcar-sr/JustifiedTextView/pull/3/commits/a40de58280ebe7f97c8ad5eec23ecdc8edae26af)

Don't worry I understand people gets busy sometimes... even more when you are a dev xD

Thank you very much!
Regards

2017-03-27 18:08 UTC, merged